name: pr_benchmark_comment

on:
  workflow_run:
    workflows: [pr_benchmarks]
    types:
      - completed

jobs:
  comment_pr:
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/github-script@v6
        with:
          script: |
            let allArtifacts = await github.rest.actions.listWorkflowRunArtifacts({
               owner: context.repo.owner,
               repo: context.repo.repo,
               run_id: context.payload.workflow_run.id,
            });
            let matchArtifact = allArtifacts.data.artifacts.filter((artifact) => {
              return artifact.name == "comment_log"
            })[0];
            let download = await github.rest.actions.downloadArtifact({
               owner: context.repo.owner,
               repo: context.repo.repo,
               artifact_id: matchArtifact.id,
               archive_format: 'zip',
            });
            let fs = require('fs');
            fs.writeFileSync(`${process.env.GITHUB_WORKSPACE}/comment_log.zip`, Buffer.from(download.data));

      - name: Unzip artifact
        run: unzip comment_log.zip

      - id: get-comment-body
        run: |
          body="$(cat asv_compare.log)"
          body="${body//'%'/'%25'}"
          body="${body//$'\n'/'%0A'}"
          body="${body//$'\r'/'%0D'}" 
          echo "::set-output name=body::$body"

      - id: get-pr-number
        run: |
          number="$(cat pr_number)"
          echo "::set-output name=number::$number"

      - name: Find Comment
        uses: peter-evans/find-comment@v2
        id: fc
        with:
          issue-number: ${{ steps.get-pr-number.outputs.number }}
          comment-author: 'github-actions[bot]'

      - name: Create comment
        if: steps.fc.outputs.comment-id == ''
        uses: peter-evans/create-or-update-comment@v2
        with:
          issue-number: ${{ steps.get-pr-number.outputs.number }}
          body: |
            ${{ steps.get-comment-body.outputs.body }}

      - name: Update comment
        if: steps.fc.outputs.comment-id != ''
        uses: peter-evans/create-or-update-comment@v2
        with:
          comment-id: ${{ steps.fc.outputs.comment-id }}
          body: |
            ${{ steps.get-comment-body.outputs.body }}
          edit-mode: replace
